const actionTypes = Object.freeze({
    GET_INFO_USER_SUCCESS: "GET_INFO_USER_SUCCESS",
    GET_INFO_USER_FAIL: "GET_INFO_USER_FAIL",

    GET_TYPE_HOTEL_SUCCESS: "GET_TYPE_HOTEL_SUCCESS",
    GET_TYPE_HOTEL_FAIL: "GET_TYPE_HOTEL_FAIL",

    GET_CONVENIENT_SUCCESS: "GET_CONVENIENT_SUCCESS",
    GET_CONVENIENT_FAIL: "GET_CONVENIENT_FAIL",

    GET_LIST_SEARCH_HOTEL_SUCCESS: "GET_LIST_SEARCH_HOTEL_SUCCESS",
    GET_LIST_SEARCH_HOTEL_FAIL: "GET_LIST_SEARCH_HOTEL_FAIL",

    GET_TOP_HOTEL_SUCCESS: "GET_TOP_HOTEL_SUCCESS",
    GET_TOP_HOTEL_FAIL: "GET_TOP_HOTEL_FAIL",

    GET_LIST_FILTER_HOTEL_SUCCESS: "GET_LIST_FILTER_HOTEL_SUCCESS",
    GET_LIST_FILTER_HOTEL_FAIL: "GET_LIST_FILTER_HOTEL_FAIL",

    GET_TOP_PROVINCES_SUCCESS: "GET_TOP_PROVINCES_SUCCESS",
    GET_TOP_PROVINCES_FAIL: "GET_TOP_PROVINCES_FAIL",

    GET_ROOM_INFO_SUCCESS: "GET_ROOM_INFO_SUCCESS",
    GET_ROOM_INFO_FAIL: "GET_ROOM_INFO_FAIL",

    GET_HOTEL_BY_MANAGER_ID_SUCCESS: "GET_HOTEL_BY_MANAGER_ID_SUCCESS",
    GET_HOTEL_BY_MANAGER_ID_SUCCESS_FAIL: "GET_HOTEL_BY_MANAGER_ID_SUCCESS_FAIL",
})

export default actionTypes;