const actionTypes = Object.freeze({
    GET_INFO_USER_SUCCESS: "GET_INFO_USER_SUCCESS",
    GET_INFO_USER_FAIL: "GET_INFO_USER_FAIL",

    GET_TYPE_HOTEL_SUCCESS: "GET_TYPE_HOTEL_SUCCESS",
    GET_TYPE_HOTEL_FAIL: "GET_TYPE_HOTEL_FAIL",

    GET_CONVENIENT_SUCCESS: "GET_CONVENIENT_SUCCESS",
    GET_CONVENIENT_FAIL: "GET_CONVENIENT_FAIL",

    GET_LIST_SEARCH_HOTEL_SUCCESS: "GET_LIST_SEARCH_HOTEL_SUCCESS",
    GET_LIST_SEARCH_HOTEL_FAIL: "GET_LIST_SEARCH_HOTEL_FAIL",

    GET_TOP_HOTEL_SUCCESS: "GET_TOP_HOTEL_SUCCESS",
    GET_TOP_HOTEL_FAIL: "GET_TOP_HOTEL_FAIL",

    GET_LIST_FILTER_HOTEL_SUCCESS: "GET_LIST_FILTER_HOTEL_SUCCESS",
    GET_LIST_FILTER_HOTEL_FAIL: "GET_LIST_FILTER_HOTEL_FAIL",

    GET_TOP_PROVINCES_SUCCESS: "GET_TOP_PROVINCES_SUCCESS",
    GET_TOP_PROVINCES_FAIL: "GET_TOP_PROVINCES_FAIL",

    GET_ROOM_INFO_SUCCESS: "GET_ROOM_INFO_SUCCESS",
    GET_ROOM_INFO_FAIL: "GET_ROOM_INFO_FAIL",

    GET_HOTEL_BY_MANAGER_ID_SUCCESS: "GET_HOTEL_BY_MANAGER_ID_SUCCESS",
    GET_HOTEL_BY_MANAGER_ID_SUCCESS_FAIL: "GET_HOTEL_BY_MANAGER_ID_SUCCESS_FAIL",

    SET_BOOKING_USER_INFO_SUCCESS: "SET_BOOKING_USER_INFO_SUCCESS",
    SET_BOOKING_USER_INFO_SUCCESS_FAIL: "SET_BOOKING_USER_INFO_SUCCESS_FAIL",

    GET_HISTORY_SEARCH_SUCCESS: "GET_HISTORY_SEARCH_SUCCESS",
    GET_HISTORY_SEARCH_FAIL: "GET_HISTORY_SEARCH_FAIL",

    TAKE_WISH_LIST_SUCCESS: "TAKE_WISH_LIST_SUCCESS",
    TAKE_WISH_LIST_FAIL: "TAKE_WISH_LIST_FAIL",

    GET_WISH_LIST_SUCCESS: "GET_WISH_LIST_SUCCESS",
    GET_WISH_LIST_FAIL: "GET_WISH_LIST_FAIL",
})

export default actionTypes;